build_mumps:
  tags:
    - linux
  script: 
    # - export CC=/usr/bin/clang
    # - export CXX=/usr/bin/clang++    
    - cd solver-external-mumps
    - cmake .
    - make 
    - ctest --output-on-failure 

build_trilinos:
  tags:
    - linux
  script: 
    # - export CC=/usr/bin/clang
    # - export CXX=/usr/bin/clang++    
    - cd solver-external-trilinos
    - cmake .
    - make 
    - ctest --output-on-failure 
    
build_petsc:
  tags:
    - linux
  script:    
    - cd solver-external-petsc
    - cmake .
    - make 
    - ctest --output-on-failure 

build:
  tags:
    - linux
  script: 
    - git submodule update --init 
    - cd dealii 
    - mkdir -p build 
    - cd build 
    - cmake -DCMAKE_BUILD_TYPE="Release" -DDEAL_II_WITH_CXX14="OFF" -DDEAL_II_WITH_CXX17="OFF" ..
    - make -j12 
    - cd ../../
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++     
    - cmake . 
    - make -j12    
    # generator
    - ./agros_generator
    - cd plugins
    - cmake .
    - make -j12
    # appimage 
    - cd ..
    - strip libs/*.so
    - strip agros
    - strip agros_solver
    - strip pythonlab
    - ./tools.py appimage
    - mkdir -p ~/appimage/$CI_BUILD_REF
    - cp Agros-x86_64.AppImage ~/appimage/$CI_BUILD_REF 
    # - curl -T Agros-x86_64.AppImage --ftp-create-dirs ftp://agros2d.org-www-version-builds:hjS888jj9888jhhg7g;@agros2d.org/$CI_BUILD_REF/Agros-x86_64.AppImage
    # test
    - cd tests
    - cmake .
    - ctest --output-on-failure
