build:
  script: 
    - git submodule update --init 
    - cd dealii 
    - mkdir -p build 
    - cd build 
    - cmake 
    - make -j30 
    - cd ../../
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++     
    - cmake . 
    - make -j30
    - ./agros2d_generator
    - cd plugins
    - cmake .
    - make -j30
    - cd ..
    - ctest -D Experimental
    
build_mumps:
  script: 
    - cd solver-external-mumps
    - cmake .
    - make 
    - ctest
