variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: fetch
  # GIT_CLEAN_FLAGS: -ffdx -e dealii/build
  GIT_CLEAN_FLAGS: none

build-linux:
  stage: build
  tags:
    - agros
  
  # Use ccache transparently, and print stats before/after
  before_script:
    - export PATH="/usr/lib/ccache:$PATH"
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - export CCACHE_COMPILERCHECK=content
    - ccache --zero-stats || true
    - ccache --show-stats || true
  after_script:
    - export CCACHE_DIR="$PWD/ccache"
    - ccache --show-stats  
  script: 
    - git submodule update --init 
    - cd dealii 
    - mkdir -p build 
    - cd build 
    - cmake -DCMAKE_BUILD_TYPE="Release" -DDEAL_II_WITH_ZLIB="ON" -DDEAL_II_WITH_UMFPACK="OFF" -DDEAL_II_FORCE_BUNDLED_BOOST="ON" -DDEAL_II_WITH_TBB="ON" -DDEAL_II_WITH_GMSH="OFF" -DDEAL_II_WITH_MUPARSER="OFF" -DDEAL_II_WITH_ARPACK="OFF" -DDEAL_II_COMPONENT_EXAMPLES="OFF" ..
    - make -j12
    - cd ../../
    - export CC=/usr/bin/clang
    - export CXX=/usr/bin/clang++     
    - cmake . 
    - make -j12    
    # generator
    - ./agros_generator
    - cd plugins
    - cmake .
    - make -j12
    - cd ..
    # appimage 
    # - cd ..
    # - strip libs/*.so
    # - strip agros
    # - strip agros_solver
    # - strip pythonlab
    # - ./tools.py appimage
    # - mkdir -p ~/appimage/$CI_BUILD_REF
    # - cp Agros-x86_64.AppImage ~/appimage/$CI_BUILD_REF 
    # - curl -T Agros-x86_64.AppImage --ftp-create-dirs ftp://agros2d.org-www-version-builds:hjS888jj9888jhhg7g;@agros2d.org/$CI_BUILD_REF/Agros-x86_64.AppImage
    # test        
    # - ln -sfn ../libs/ agrossuite/libs
    # - ln -sfn ../dealii/build/lib/libdeal_II.so.9.5.2 libs/libdeal_II.so.9.5.2
    # - cd agrossuite/tests    
    # - pytest-3 --disable-warnings --durations=0 -v
    
test:
  stage: test
  tags:
    - agros

  script: 
    - ln -sfn ../libs/ agrossuite/libs
    - ln -sfn ../dealii/build/lib/libdeal_II.so.9.5.2 libs/libdeal_II.so.9.5.2
    - cd agrossuite/tests    
    - pytest-3 --junitxml=report.xml --disable-warnings --durations=0 -v
  artifacts:
    when: always
    reports:
      junit: report.xml
    
# build-windows:
#   stage: build
#   tags:
#    - agros-windows
#
#  before_script:
#    - dir    
#  after_script:
#    - dir
#    script:
#    - dir   
