build:
  script: 
    - git submodule update --init 
    - cd dealii 
    - mkdir build 
    - cd build 
    - cmake 
    - make -j20 
    - cd ../../ 
    - cmake . 
    - make -j20
    - ctest -D Experimental
  
